### ISSUE TITLE
Chuting into a Trading Floor Crashes the Game

### ISSUE THREAD

**Issue by FoxTheUnicorn** [cakeGit/Create-Trading-Floor#5] opened 2024-11-10 19:05 UTC
When you place a trading floor under a chute and drop an item into the chute it crashes the game.

Steps to reproduce:
1. Place a Chute on top of a stone block
2. Break the block below the Chute
3. Place a Trading Floor below the Chute
4. Drop an Item in the Chute

This also just so happens to crash the game whenever it loads the world (which I figured out the hard way)
Funnily enough if you place the Trading Floor first and the Chute afterwards it does not crash.

[Crash Log](https://github.com/user-attachments/files/17692676/crash-2024-11-10_20.01.11-server.txt)
[Video of Reproduction](https://youtu.be/t6fpDCyNPh0)

Edit:
it appears that this extends to all forms of item transfers. I tested it with Anesite funnels and also with a hopper.

**Comment by LegacyKing** [comment] 2024-11-14 02:08
I can confirm this behavior, here's the crash log:

```
java.lang.NullPointerException: Cannot assign field "stack" because "this.offer" is null
	at TRANSFORMER/trading_floor@1.1.2+forge-1.20.1/com.cak.trading_floor.forge.content.depot.behavior.TradingDepotBehaviour.setOfferStack(TradingDepotBehaviour.java:261)
	at TRANSFORMER/trading_floor@1.1.2+forge-1.20.1/com.cak.trading_floor.forge.content.depot.TradingDepotItemHandler.insertItem(TradingDepotItemHandler.java:44)
	at TRANSFORMER/forge@47.2.0/net.minecraftforge.items.ItemHandlerHelper.insertItemStacked(ItemHandlerHelper.java:124)
	at TRANSFORMER/create@0.5.1.j/com.simibubi.create.content.logistics.chute.ChuteBlockEntity.handleDownwardOutput(ChuteBlockEntity.java:376)
	at TRANSFORMER/create@0.5.1.j/com.simibubi.create.content.logistics.chute.ChuteBlockEntity.tick(ChuteBlockEntity.java:167)
	at TRANSFORMER/create@0.5.1.j/com.simibubi.create.foundation.blockEntity.SmartBlockEntityTicker.m_155252_(SmartBlockEntityTicker.java:15)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.mixinextras$bridge$m_155252_$11(LevelChunk.java)
	at TRANSFORMER/neruina@2.1.2/com.bawnorton.neruina.handler.TickHandler.safelyTickBlockEntity(TickHandler.java:169)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.wrapOperation$zlp000$catchTickingBlockEntity$notTheCauseOfTickLag(LevelChunk.java:815)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:689)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:782)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.Level.m_46463_(Level.java:468)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:351)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:283)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by cakeGit** [comment] 2024-11-14 06:56
Thanks for the report, could you please update your version of the mod? since this may have been fixed in a later version, and I noticed that this both happens on 1.1.2

**Comment by FoxTheUnicorn** [comment] 2024-11-14 07:03
This was tested with the version 1.1.2 of the mod. If you want me to update to a newer version. I cannot find a release higher than 1.1.2 anywhere.

**Comment by cakeGit** [comment] 2024-11-14 07:09
Nevermind I got confused with another project, I'll try get a fix together today,

**Comment by cakeGit** [comment] 2024-11-14 07:50
Hopefully the 1.1.3 version just released should fix your issue

**Comment by LegacyKing** [comment] 2024-11-14 08:22
I'll give it a go now. (*Should be in bed since it's after midnight, but a quick test isn't hard to do)

**Comment by LegacyKing** [comment] 2024-11-14 08:56
Connected, no errors on load. Added the smart chute and regular chute, no errors. Played in the world for a bit, no errors. Disconnected and reconnected, no errors. For me, this patch worked. I'd wait on @FoxTheUnicorn to confirm it works (since they're the OP) but I'm happy it's working again! :)

**Comment by cakeGit** [comment] 2024-11-14 09:00
Ill take this as it being fixed since it was just a check in the fabric version missing in forge, sleep well!

**Closed as completed by cakeGit** 2024-11-14 09:00 UTC

**Comment by FoxTheUnicorn** [comment] 2024-11-14 10:49
Yup works as expected now.
